// Slice 2d — Sandbox abstract interface for executing Python code-tests
// generated by the model under characterization. See
// SEMANTIC_ROUTING_FEATURES/SECURITY-sandbox-2d.md (threat model) and
// DECISIONS.md Dαα (ratification). Architecture inspired by deer-flow's
// abstract `Sandbox` base + swappable providers, but the actual isolation
// is kernel-enforced (POSIX rlimits / Windows Job Object) — deer-flow's
// own LocalSandbox is a subprocess wrapper without real isolation.
//
// Honest contract: ANY failure to establish the OS boundary MUST throw
// `SandboxUnavailable`. The caller (staircase.ts) translates that into
// an UNMEASURED verdict (`sandbox-pending`) so the leaf is left as a
// branch prior (D12), NEVER as a false pass.

export type SandboxOptions = {
  /** Wall-clock timeout per item, ms. Default 10_000. */
  timeoutMs?: number;
  /** Max combined stdout+stderr bytes before the child is killed. Default 1_000_000. */
  maxOutputBytes?: number;
  /** Per-process CPU seatbelt seconds (POSIX `RLIMIT_CPU`). Default 10. */
  cpuLimitSeconds?: number;
  /** Address-space cap, bytes. Default 512 MiB. */
  memoryLimitBytes?: number;
};

export type SandboxResult = {
  /** True iff python exited 0 (i.e. all asserts passed). */
  pass: boolean;
  /** Captured stdout, capped to a debug-friendly size. */
  stdout: string;
  /** Captured stderr, capped to a debug-friendly size. */
  stderr: string;
  /** Wall-clock duration, ms. */
  durationMs: number;
  /**
   * Why `pass` is false (when it is). Diagnostic only — never enters
   * routing logic. Values: 'exit-nonzero' | 'timeout' | 'output-overflow'
   * | 'unknown'.
   */
  reason?: 'exit-nonzero' | 'timeout' | 'output-overflow' | 'unknown';
};

/**
 * Thrown by a provider when the OS-level boundary cannot be established.
 *
 * Examples that MUST throw this (per SECURITY-sandbox-2d.md couche C —
 * "fail-closed"):
 *  - POSIX: `resource` module unavailable, `setrlimit` raises, `setsid`
 *    fails, mkdtemp KO, python binary not found / not POSIX.
 *  - Windows: PowerShell unavailable, P/Invoke layer raises, Job Object
 *    creation fails, `AssignProcessToJobObject` fails before child
 *    runs anything, python.exe not found.
 *  - Either platform: the active provider is `UnsafeSandbox` (i.e. the
 *    Settings opt-in toggle is OFF).
 *
 * Examples that MUST NOT throw this (instead return `{pass: false}`):
 *  - The python script itself raises an exception or fails an assert.
 *  - The script times out (we killed it — that IS the sandbox working).
 *  - The script tries to fork/network/write and we blocked it.
 */
export class SandboxUnavailable extends Error {
  constructor(reason: string) {
    super(`sandbox unavailable: ${reason}`);
    this.name = 'SandboxUnavailable';
  }
}

/**
 * Provider interface. One subclass per isolation strategy. The renderer
 * never imports these directly; they are constructed by `getSandbox()`
 * in `index.ts` based on `process.platform` and the Settings opt-in.
 */
export abstract class SandboxProvider {
  /**
   * Execute `code` (the model's `def solve(...)` definition) plus
   * `tests` (curated assert block) inside the isolated environment.
   *
   * Returns `{pass: true}` iff the child exited 0 within the limits.
   * Returns `{pass: false, reason: …}` for any in-sandbox failure
   * (non-zero exit, timeout we enforced, output overflow we enforced).
   *
   * Throws `SandboxUnavailable` iff the OS boundary couldn't be
   * established at all (caller marks the item UNMEASURED — D12 prior).
   */
  abstract runPythonTests(
    code: string,
    tests: string,
    opts?: SandboxOptions,
  ): Promise<SandboxResult>;

  /** Short human-readable identifier for logs (`'posix'` | `'windows'` | `'unsafe'`). */
  abstract readonly kind: string;
}
